import * as flsFunctions from './modules/functions.js'
import '../../node_modules/bootstrap/js/src/collapse.js'
import '../../node_modules/bootstrap/js/src/dropdown.js'
import '../../node_modules/slick-carousel/slick/slick.js'
import './modules/rev-slider.js'
import './modules/price-slider.js'
